import { describe, expect, it } from "vitest";
import { adapter as codex } from "../../src/adapters/codex/adapter.js";
import { adapter as claude } from "../../src/adapters/claude/adapter.js";
import { adapter as hermes } from "../../src/adapters/hermes/adapter.js";

const context = (files: Record<string, string>, directories: Record<string, readonly string[]> = {}) => { const root = {} as never; const safeFs = { admitRoot: async () => ({ ok: true as const, root }), readText: async (_root: unknown, path: string) => files[path] === undefined ? { ok: false as const, diagnostic: { code: "not_found" as const } } : { ok: true as const, text: files[path] }, readDirectory: async (_root: unknown, path: string) => directories[path] === undefined ? { ok: false as const, diagnostic: { code: "not_found" as const } } : { ok: true as const, entries: directories[path] } }; return { safeFs, genericProjectRoot: "/repo" } as never; };

describe("live adapter file projections", () => {
  it("marks partial coverage when Codex finds only a supported surface", async () => { const result = await codex.scan(context({ "AGENTS.md": "rules" })); expect(result.inventory).toHaveLength(1); expect(result.inventory[0]?.agent).toBe("codex"); expect(result.coverage).toBe("partial"); });
  it("projects Codex TOML configuration", async () => { const result = await codex.scan(context({ "config.toml": "profile = \"default\"" })); expect(result.inventory.some((entry) => entry.kind === "configuration")).toBe(true); });
  it("projects Codex MCP servers from TOML configuration", async () => { const result = await codex.scan(context({ "config.toml": "[mcp_servers.github]\ncommand = \"npx\"\nargs = [\"-y\", \"@modelcontextprotocol/server-github@1.2.3\"]\n[mcp_servers.remote]\nurl = \"https://mcp.example.test/api\"" })); expect(result.inventory.filter((entry) => entry.kind === "mcp")).toMatchObject([{ kind: "mcp", name: "github", facts: { transport: "stdio", packageInvocation: "exact" } }, { kind: "mcp", name: "remote", facts: { transport: "http", urlClass: "tls" } }]); });
  it("projects Codex user skills from admitted directory entries", async () => { const result = await codex.scan(context({ ".agents/skills/demo/SKILL.md": "skill" }, { ".agents/skills": ["demo"] })); expect(result.inventory).toMatchObject([{ facts: { type: "skill", effectiveName: "demo" } }]); });
  it("marks partial coverage when Claude finds only a supported surface", async () => { const result = await claude.scan(context({ "CLAUDE.md": "rules" })); expect(result.inventory).toHaveLength(1); expect(result.inventory[0]?.agent).toBe("claude"); expect(result.coverage).toBe("partial"); });
  it("projects Claude JSON settings", async () => { const result = await claude.scan(context({ "settings.json": "{}" })); expect(result.inventory.some((entry) => entry.kind === "configuration")).toBe(true); });
  it("projects Claude MCP servers from project .mcp.json", async () => { const result = await claude.scan(context({ ".mcp.json": "{\"mcpServers\":{\"demo\":{\"command\":\"npx\",\"args\":[\"demo@latest\"]}}}" })); expect(result.inventory.filter((entry) => entry.kind === "mcp")).toMatchObject([expect.objectContaining({ kind: "mcp", name: "demo", facts: expect.objectContaining({ packageInvocation: "unpinned" }) })]); });
  it("projects managed Claude settings and marks lower-precedence MCP definitions shadowed", async () => { const result = await claude.scan(context({ ".mcp.json": "{\"mcpServers\":{\"demo\":{\"command\":\"npx\",\"args\":[\"demo@latest\"]}}}", "managed-settings.json": "{\"mcpServers\":{\"demo\":{\"command\":\"npx\",\"args\":[\"demo@1.2.3\"]}}}" })); expect(result.inventory.filter((entry) => entry.kind === "mcp")).toMatchObject([{ name: "demo", scope: "project", status: "unresolved" }, { name: "demo", scope: "managed", status: "active" }]); expect(result.inventory).toContainEqual(expect.objectContaining({ kind: "configuration", source: expect.objectContaining({ relativePath: "managed-settings.json" }), scope: "managed", facts: expect.objectContaining({ precedence: 5 }) })); });
  it("projects every readable managed-settings.d JSON file", async () => { const result = await claude.scan(context({ "managed-settings.d/a.json": "{}", "managed-settings.d/b.json": "{}" }, { "managed-settings.d": ["b.json", "a.json"] })); expect(result.inventory.filter((entry) => entry.kind === "configuration" && entry.scope === "managed").map((entry) => entry.source.relativePath)).toEqual(["managed-settings.d/a.json", "managed-settings.d/b.json"]); });
  it("projects immediate user MCP definitions from the bounded Claude application file", async () => { const result = await claude.scan(context({ ".claude.json": "{\"mcpServers\":{\"user-demo\":{\"command\":\"npx\",\"args\":[\"demo@1.2.3\"]}}}" })); expect(result.inventory).toContainEqual(expect.objectContaining({ kind: "mcp", name: "user-demo", scope: "user", source: expect.objectContaining({ rootId: "home", relativePath: ".claude.json" }) })); });
  it("projects Claude user skills from admitted directory entries", async () => { const result = await claude.scan(context({ "skills/demo/SKILL.md": "skill" }, { "skills": ["demo"] })); expect(result.inventory).toMatchObject([{ facts: { type: "skill", effectiveName: "demo" } }]); });
  it("projects Hermes YAML configuration", async () => { const result = await hermes.scan(context({ "config.yaml": "enabled: true" })); expect(result.inventory.some((entry) => entry.kind === "configuration")).toBe(true); });
  it("marks partial coverage when Hermes finds only a supported surface", async () => { const result = await hermes.scan(context({ "SOUL.md": "soul" })); expect(result.inventory).toHaveLength(1); expect(result.inventory[0]?.agent).toBe("hermes"); expect(result.coverage).toBe("partial"); });
  it("projects Hermes MCP servers from YAML configuration", async () => { const result = await hermes.scan(context({ "config.yaml": "mcp_servers:\n  demo:\n    command: npx\n    args:\n      - demo@latest" })); expect(result.inventory.filter((entry) => entry.kind === "mcp")).toMatchObject([expect.objectContaining({ kind: "mcp", name: "demo", facts: expect.objectContaining({ packageInvocation: "unpinned" }) })]); });
  it("keeps optional Hermes MCP manifests as deferred catalog candidates", async () => { const result = await hermes.scan(context({ "optional-mcps/demo/manifest.yaml": "name: Demo" }, { "optional-mcps": ["demo"] })); expect(result.inventory).toMatchObject([expect.objectContaining({ kind: "mcp", name: "demo", status: "candidate", loading: "deferred", source: expect.objectContaining({ relativePath: "optional-mcps/demo/manifest.yaml" }) })]); });
  it("keeps sticky Hermes active profiles unresolved and sibling profiles as candidates", async () => { const result = await hermes.scan(context({ "active_profile": "work\n", "profiles/work/config.yaml": "mcp_servers:\n  work:\n    command: npx", "profiles/other/config.yaml": "mcp_servers:\n  other:\n    command: npx" }, { "profiles": ["other", "work"] })); expect(result.inventory.filter((entry) => entry.kind === "mcp")).toMatchObject([{ name: "other", status: "candidate", source: expect.objectContaining({ relativePath: "profiles/other/config.yaml" }) }, { name: "work", status: "unresolved", source: expect.objectContaining({ relativePath: "profiles/work/config.yaml" }) }]); });
  it("projects Hermes user skills from admitted directory entries", async () => { const result = await hermes.scan(context({ "skills/demo/SKILL.md": "skill" }, { "skills": ["demo"] })); expect(result.inventory).toMatchObject([{ facts: { type: "skill", effectiveName: "demo" } }]); });  it("keeps unapproved Claude project MCPs unresolved and activates only explicit approval", async () => {
    const files = { ".mcp.json": "{\"mcpServers\":{\"demo\":{\"command\":\"node\"}}}" };
    const unresolved = await claude.scan(context(files));
    const approved = await claude.scan(context({ ...files, ".claude.json": "{\"projects\":{\"/repo\":{\"hasTrustDialogAccepted\":true}}}" }));
    expect(unresolved.inventory.find((entry) => entry.kind === "mcp")?.status).toBe("unresolved");
    expect(approved.inventory.find((entry) => entry.kind === "mcp" && entry.source.rootId === "project")?.status).toBe("active");
  });
  it("keeps Hermes MCPs with environment references unresolved", async () => {
    const result = await hermes.scan(context({ "config.yaml": "mcp_servers:\n  dynamic:\n    command: ${MCP_COMMAND}" }));
    expect(result.inventory.find((entry) => entry.kind === "mcp")?.status).toBe("unresolved");
  });
});